// TPGZ 1.2.0-dev item-wheel table and defaults (GPL-3.0). Native enum names.
#pragma once
#include "d/d_item_data.h"
namespace gz {
struct WheelItem {u8 item;const char* label;};
inline constexpr WheelItem wheelItems[]={
 {dItemNo_NONE_e, "n/a"},
 {dItemNo_ANCIENT_DOCUMENT_e, "ancient sky book (empty)"},
 {dItemNo_ANCIENT_DOCUMENT2_e, "ancient sky book (filled)"},
 {dItemNo_AIR_LETTER_e, "ancient sky book (partial)"},
 {dItemNo_ASHS_SCRIBBLING_e, "ashei's sketch"},
 {dItemNo_RAFRELS_MEMO_e, "auru's memo"},
 {dItemNo_IRONBALL_e, "ball and chain"},
 {dItemNo_BEE_CHILD_e, "bee larva"},
 {dItemNo_CHUCHU_BLUE_e, "blue chu"},
 {dItemNo_BLUE_BOTTLE_e, "blue potion"},
 {dItemNo_POKE_BOMB_e, "bomblings"},
 {dItemNo_HOOKSHOT_e, "clawshot"},
 {dItemNo_COPY_ROD_e, "dominion rod"},
 {dItemNo_W_HOOKSHOT_e, "double clawshot"},
 {dItemNo_BOMB_BAG_LV1_e, "empty bomb bag"},
 {dItemNo_EMPTY_BOTTLE_e, "empty bottle"},
 {dItemNo_FAIRY_e, "fairy"},
 {dItemNo_FAIRY_DROP_e, "fairy tears"},
 {dItemNo_FISHING_ROD_1_e, "fishing rod"},
 {dItemNo_BEE_ROD_e, "fishing rod (bee larva)"},
 {dItemNo_JEWEL_ROD_e, "fishing rod (coral earring)"},
 {dItemNo_JEWEL_BEE_ROD_e, "fishing rod (coral earring/bee larva)"},
 {dItemNo_JEWEL_WORM_ROD_e, "fishing rod (coral earring/worm)"},
 {dItemNo_WORM_ROD_e, "fishing rod (worm)"},
 {dItemNo_BOOMERANG_e, "gale boomerang"},
 {dItemNo_LV2_SOUP_e, "good soup"},
 {dItemNo_CHUCHU_GREEN_e, "green chu"},
 {dItemNo_HALF_MILK_BOTTLE_e, "half milk"},
 {dItemNo_HAWK_EYE_e, "hawkeye"},
 {dItemNo_BOW_e, "hero's bow"},
 {dItemNo_HORSE_FLUTE_e, "horse call"},
 {dItemNo_HOT_SPRING_e, "hot spring water"},
 {dItemNo_IRIAS_PENDANT_e, "Ilia's charm"},
 {dItemNo_BILL_e, "invoice"},
 {dItemNo_HVY_BOOTS_e, "iron boots"},
 {dItemNo_KANTERA_e, "lantern"},
 {dItemNo_OIL_BOTTLE_e, "lantern oil"},
 {dItemNo_GREEN_BOTTLE_e, "magic potion"},
 {dItemNo_MILK_BOTTLE_e, "milk"},
 {dItemNo_UGLY_SOUP_e, "nasty soup"},
 {dItemNo_DUNGEON_BACK_e, "ooccoo Jr."},
 {dItemNo_DUNGEON_EXIT_e, "ooccoo Sr."},
 {dItemNo_TKS_LETTER_e, "ooccoo's note"},
 {dItemNo_CHUCHU_PURPLE_e, "purple chu"},
 {dItemNo_CHUCHU_RARE_e, "rare chu"},
 {dItemNo_CHUCHU_RED_e, "red chu"},
 {dItemNo_RED_BOTTLE_e, "red potion"},
 {dItemNo_NORMAL_BOMB_e, "regular bombs"},
 {dItemNo_LETTER_e, "renado's letter"},
 {dItemNo_LV1_SOUP_e, "simple soup"},
 {dItemNo_PACHINKO_e, "slingshot"},
 {dItemNo_SPINNER_e, "spinner"},
 {dItemNo_LV3_SOUP_e, "superb soup"},
 {dItemNo_WATER_BOTTLE_e, "water"},
 {dItemNo_WATER_BOMB_e, "water bombs"},
 {dItemNo_WOOD_STATUE_e, "wooden statue"},
 {dItemNo_WORM_e, "worm"},
 {dItemNo_CHUCHU_YELLOW_e, "yellow chu"},
};
inline constexpr u8 wheelDefaults[]={dItemNo_BOOMERANG_e,dItemNo_KANTERA_e,dItemNo_SPINNER_e,dItemNo_HVY_BOOTS_e,dItemNo_BOW_e,dItemNo_HAWK_EYE_e,dItemNo_IRONBALL_e,dItemNo_NONE_e,dItemNo_COPY_ROD_e,dItemNo_HOOKSHOT_e,dItemNo_W_HOOKSHOT_e,dItemNo_EMPTY_BOTTLE_e,dItemNo_EMPTY_BOTTLE_e,dItemNo_EMPTY_BOTTLE_e,dItemNo_EMPTY_BOTTLE_e,dItemNo_NORMAL_BOMB_e,dItemNo_WATER_BOMB_e,dItemNo_POKE_BOMB_e,dItemNo_DUNGEON_EXIT_e,dItemNo_RAFRELS_MEMO_e,dItemNo_FISHING_ROD_1_e,dItemNo_HORSE_FLUTE_e,dItemNo_ANCIENT_DOCUMENT_e,dItemNo_PACHINKO_e,};
static_assert(sizeof(wheelDefaults)==24);
}
