// Native upstream TP routines with only the GZ fast-movement parameter reads replaced.
// Generated by tools/adapt-link-movement.py. GPL-3.0.
#include "core.hpp"
#include "movement_settings.hpp"
#include "d/actor/d_a_horse.h"
#include "d/actor/d_a_alink.h"
#include "d/d_com_inf_game.h"
#include "d/d_camera.h"
#include "d/d_meter2_info.h"
#include "SSystem/SComponent/c_math.h"
#include "f_op/f_op_kankyo_mng.h"

int daAlink_c::setStartProcInit() {
    BOOL sp10 = FALSE;
    int start_mode = getStartMode();
    u32 last_mode = getLastSceneMode();
    daHorse_c* horsep = (daHorse_c*)dComIfGp_getHorseActor();
    BOOL isHorseStart = checkHorseStart(last_mode, start_mode);

    setDamagePoint(getLastSceneDamage(), last_mode == 4, FALSE, 1);
    mSwordUpTimer = getLastSceneSwordAtUpTime() * 2;

    if (checkWolf()) {
        setFaceBasicAnime(ANM_WAIT);
    } else {
        mEquipItem = (dComIfGs_getLastSceneMode() >> 0x18) & 0xFF;
        if (mEquipItem == dItemNo_SWORD_e) {
            mEquipItem = 0x103;
        } else if (checkStageName("D_MN09B") && last_mode != 8 && start_mode == 2) {
            mEquipItem = 0x103;
        }

        if (mEquipItem == 0
            || !checkCastleTownUseItem(mEquipItem)
            || (checkCloudSea() && mEquipItem != 0x103)
            || checkCanoeStart()
            || (isHorseStart
                && mEquipItem != 0x103
                && !checkBowAndSlingItem(mEquipItem)
                && mEquipItem != dItemNo_BOOMERANG_e
                && mEquipItem != dItemNo_KANTERA_e
                && !checkHookshotItem(mEquipItem))
            )
        {
            mEquipItem = dItemNo_NONE_e;
        } else {
            setItemModel();
        }

        if (isHorseStart) {
            horsep->setHorsePosAndAngle(&current.pos, shape_angle.y);
            horsep->initHorseMtx();
            initForceRideHorse();
        }
    }

    if (last_mode == 6) {
        procCoPeepSubjectivityInit();
    } else if (last_mode == 11) {
        mLinkAcch.SetGroundHit();
        procBoardWaitInit(fopAcM_SearchByID(mRideActorID));
    } else if (last_mode == 12) {
        procDungeonWarpSceneStartInit();
    } else if (dComIfGp_getStartStagePoint() == -4) {
        procCoWarpInit(1, 1);
    } else if (start_mode == 8 && mStartEventID == 0xFF) {
        procCoWarpInit(1, 0);
    } else if (last_mode == 4 || start_mode == 12 || last_mode == 5) {
        if (checkHorseRide()) {
            procHorseComebackInit();
        } else {
            commonLargeDamageUpInit(-2, TRUE, 0, 0);
            if (checkWolf()) {
                sp10 = TRUE;
            }
        }
    } else if (last_mode == 9) {
        procWolfDigThroughInit(1);
    } else if (last_mode == 8) {
        initForceRideHorse();
        procHorseComebackInit();
    } else if (last_mode == 10) {
        checkWaitAction();
    } else if (start_mode == 9) {
        if (checkWolf()) {
            procWolfTagJumpInit(NULL);
        } else {
            procAutoJumpInit(1);
        }
    } else if (start_mode == 4) {
        if (checkWolf()) {
            procWolfAutoJumpInit(1);
        } else {
            procAutoJumpInit(1);
        }
        mNormalSpeed = 55.0f;
        speed.y = 0.0f;
    } else if (checkCanoeStart()) {
        procCanoeJumpRideInit(NULL);
    } else if (checkBoarStart()) {
        if (!initForceRideBoar()) {
            procWaitInit();
        } else {
            procHorseWaitInit();
        }
    } else if (start_mode == 1 || start_mode == 3 || start_mode == 5 || start_mode == 14 || start_mode == 13 || start_mode == 2 || start_mode == 0) {
        if (start_mode == 3) {
            shape_angle.y = dComIfGs_getLastSceneAngleY();
            current.angle.y = shape_angle.y;
            mPrevAngleY = shape_angle.y;
        }

        if (mStartEventID == 0xFF) {
            if (!checkModeFlg(0x400) && start_mode != 0) {
                mNormalSpeed = dComIfGs_getLastSceneSpeedF();
            }

            mDemo.setStartDemoType();
            mDemo.setDemoMode(daPy_demo_c::DEMO_UNK_14_e);
            mDemo.setMoveAngle(current.angle.y);
            mDemo.setTimer(35);

            if (checkModeFlg(0x400)) {
                daHorse_c* horse = dComIfGp_getHorseActor();
                horse->changeOriginalDemo();
                horse->changeDemoMode(6, 0);

                if (start_mode == 2) {
                    if (checkStageName("F_SP109") && fopAcM_GetRoomNo(this) == 0 && dComIfGs_getStartPoint() == 35) {
                        horse->setSpeedF(horse->getNormalMaxSpeedF());
                    } else {
                        horse->setSpeedF(0.0f);
                    }
                } else if (start_mode == 1) {
                    horse->setWalkSpeedF();
                } else {
                    horse->setSpeedF(dComIfGs_getLastSceneSpeedF());
                }

                procHorseWaitInit();
            } else if (checkSwimAction(1)) {
                if (start_mode == 1) {
                    if (checkWolf()) {
                        mNormalSpeed = 0.5f * 50.0f;
                    } else {
                        mNormalSpeed = 0.5f * 50.0f;
                    }
                }

                speedF = mNormalSpeed;

                if (checkWolf()) {
                    procWolfSwimMoveInit();
                } else if (mNormalSpeed < mpHIO->mSwim.m.mForwardMinSpeed) {
                    procSwimWaitInit(0);
                } else {
                    procSwimMoveInit();
                }

                field_0x2f99 = 0;
            } else if (start_mode == 1) {
                if (checkWolf()) {
                    mNormalSpeed = mpHIO->mWolf.mWlMove.m.mIdleToWalkRate * mpHIO->mWolf.mWlMove.m.mMaxSpeed;
                    speedF = mNormalSpeed;
                    procWolfMoveInit();
                } else {
                    mNormalSpeed = mpHIO->mMove.m.mWalkChangeRate * mpHIO->mMove.m.mMaxSpeed;
                    speedF = mNormalSpeed;
                    procMoveInit();
                }
            } else if (start_mode == 0) {
                checkWaitAction();
            } else if (last_mode == 2 || last_mode == 3) {
                mDemo.setStick(dComIfGs_getLastSceneSpeedF());
                mMoveAngle = shape_angle.y;

                if (last_mode == 3) {
                    ANGLE_ADD_2(shape_angle.y, 0x8000);
                    current.angle.y = shape_angle.y;
                    mPrevAngleY = shape_angle.y;
                }

                if (checkWolf()) {
                    procWolfLieMoveInit(0);
                } else {
                    procCrawlMoveInit(0, 0);
                }
            } else if (checkWolf()) {
                if (mNormalSpeed > mpHIO->mWolf.mWlMove.m.mMaxSpeed) {
                    mNormalSpeed = mpHIO->mWolf.mWlMove.m.mMaxSpeed;
                }
                speedF = mNormalSpeed;
                procWolfMoveInit();
            } else {
                if (mNormalSpeed > mpHIO->mMove.m.mMaxSpeed) {
                    mNormalSpeed = mpHIO->mMove.m.mMaxSpeed;
                }
                speedF = mNormalSpeed;
                procMoveInit();
            }
        } else {
            checkWaitAction();
        }
    } else {
        checkWaitAction();
    }

    return sp10;
}

void daAlink_c::initGravity() {
    f32 gravity;
    f32 max_fall_speed;

    if (checkWolf()) {
        if (checkModeFlg(MODE_SWIMMING)) {
            if (checkHeavyStateOn(TRUE, TRUE)) {
                gravity = -mpHIO->mWolf.mWlSwim.m.mHeavyBuoyancy;
                max_fall_speed = mpHIO->mWolf.mWlSwim.m.mHeavyMaxFallSpeed;
            } else {
                gravity = -mpHIO->mWolf.mWlSwim.m.mBuoyancy;
                max_fall_speed = mpHIO->mWolf.mWlSwim.m.mMaxFallSpeed;
            }
        } else {
            gravity = mpHIO->mWolf.mWlAutoJump.m.mGravity;
            max_fall_speed = mpHIO->mWolf.mWlAutoJump.m.mMaxFallSpeed;
        }
    } else if (checkModeFlg(MODE_SWIMMING) || checkNoResetFlg0(FLG0_WATER_IN_MOVE)) {
        max_fall_speed = getSwimMaxFallSpeed();
        if (checkHeavyStateOn(TRUE, TRUE) && mProcID != PROC_OCTAIEAL_SPIT) {
            gravity = -50.0f;
        } else {
            gravity = -mpHIO->mSwim.m.mBuoyancy;
        }
    } else {
        gravity = mpHIO->mAutoJump.m.mGravity;
        max_fall_speed = mpHIO->mAutoJump.m.mMaxFallSpeed;
    }

    setSpecialGravity(gravity, max_fall_speed, TRUE);
}

int daAlink_c::procFrontRollInit() {
    BOOL is_guard_anime = checkUpperGuardAnime();
#ifdef TARGET_PC    
    const f32 fastRollMultiplier = gz::movementSetting(0) ? 2.0f : 1.0f;
#endif

    if (mProcID == PROC_FRONT_ROLL && mDemo.getDemoMode() == daPy_demo_c::DEMO_FRONT_ROLL_e) {
        return 0;
    }

    BOOL is_dive_jump = mProcID == PROC_DIVE_JUMP;
    commonProcInit(PROC_FRONT_ROLL);

    f32 roll_anm_speed;
    if (is_dive_jump) {
        roll_anm_speed = 6.0f;
    } else {
        roll_anm_speed = mpHIO->mFrontRoll.m.mRollAnm.mStartFrame;
    }

    setSingleAnime(ANM_FRONT_ROLL,
#ifdef TARGET_PC        
                   mpHIO->mFrontRoll.m.mRollAnm.mSpeed * fastRollMultiplier, 
#else
                   mpHIO->mFrontRoll.m.mRollAnm.mSpeed,
#endif
                   roll_anm_speed,
                   mpHIO->mFrontRoll.m.mRollAnm.mEndFrame,
                   mpHIO->mFrontRoll.m.mRollAnm.mInterpolation);
                   
    mNormalSpeed = speedF * 3.0f + mpHIO->mFrontRoll.m.mInitSpeed;

    f32 max_speed = mpHIO->mFrontRoll.m.mInitSpeed + mpHIO->mMove.m.mMaxSpeed * 3.0f;
    if (mNormalSpeed > max_speed) {
        mNormalSpeed = max_speed;
    }

    if (mNormalSpeed < mpHIO->mFrontRoll.m.mMinSpeed) {
        mNormalSpeed = mpHIO->mFrontRoll.m.mMinSpeed;
    }

    if (checkNoResetFlg0(FLG0_WATER_IN_MOVE)) {
#if TARGET_PC
        if (!(gz::movementSetting(1)))
#endif
        {
            mNormalSpeed *= mpHIO->mItem.mIronBoots.m.mWaterVelocityX;
        }
    } else if (checkHeavyStateOn(TRUE, TRUE)) {
        mNormalSpeed *= mHeavySpeedMultiplier;
    }

#ifdef TARGET_PC        
    mNormalSpeed *= fastRollMultiplier;
#endif

    current.angle.y = shape_angle.y;
    voiceStart(Z2SE_AL_V_BACKTEN);
    mProcVar2.field_0x300c = 0;
    setFootEffectProcType(0);

    if (is_guard_anime) {
        onNoResetFlg0(FLG0_UNK_2);
    }

    if (checkEquipHeavyBoots()) {
        mAtSph.SetAtType(AT_TYPE_HEAVY_BOOTS);
        mAtSph.SetAtHitMark(1);
        mAtSph.SetAtSe(dCcD_SE_METAL);
        mAtSph.SetAtAtp(2);
        mAtSph.SetAtMtrl(dCcD_MTRL_NONE);
        mAtSph.ResetAtHit();
        mAtSph.SetR(mpHIO->mFrontRoll.m.mBootsAttackRadius);
        mAtSph.OnAtSetBit();
    }

    return 1;
}

f32 daAlink_c::getSwimFrontMaxSpeed() const {
    if (checkBootsOrArmorHeavy()) {
        return 50.0f;
    } else if (checkZoraWearAbility()) {
        return 14.0f;
    } else if (checkSwimDashMode()) {
        return 50.0f;
    } else {
        return 50.0f;
    }
}

f32 daAlink_c::getSwimMaxFallSpeed() const {
    if (mProcID == PROC_DIVE_JUMP) {
        return -50.0f;
    } else if (checkBootsOrArmorHeavy()) {
        return -50.0f;
    } else if (getZoraSwim()) {
        return mpHIO->mSwim.m.mMaxFallSpeed;
    } else {
        return mpHIO->mSwim.m.mStandingMaxFallSpeed;
    }
}

void daAlink_c::setSpeedAndAngleSwim() {
    if (!checkBootsOrArmorHeavy() && dComIfGp_getDoStatus() == BUTTON_STATUS_NONE && (!checkHookshotAnime() || (checkHookshotItem(mEquipItem) && (mItemMode == 0 || mItemMode == 1)))) {
        if (checkZoraWearAbility()) {
            if (checkNoResetFlg0(FLG0_SWIM_UP)) {
                if (field_0x2fcd == 0) {
                    setDoStatus(BUTTON_STATUS_DIVE);
                }
            } else {
                setDoStatus(BUTTON_STATUS_SWIM);
            }
        } else if (!checkNoResetFlg0(FLG0_SWIM_UP)) {
            setDoStatus(BUTTON_STATUS_UNK_151);
        } else if (mProcID == PROC_SWIM_MOVE && checkUnderMove0BckNoArc(ANM_SWIM_A) && field_0x30d0 == 0 && field_0x30d2 == 0) {
            setDoStatus(BUTTON_STATUS_DASH);
        }
    }

    f32 var_f31;
    f32 var_f30;
    s16 temp_r29;
    if (mProcID == PROC_SWIM_HOOKSHOT_MOVE && !checkHookshotWait()) {
        var_f30 = 0.0f;
    } else if (checkZoraSwimMove()) {
        temp_r29 = shape_angle.y;

        if (mTargetedActor != NULL && current.pos.abs2XZ(mTargetedActor->eyePos) > 22500.0f) {
            setShapeAngleToAtnActor(0);
        } else if (checkInputOnR()) {
            s16 var_r28;
            if (checkEventRun()) {
                var_r28 = mMoveAngle;
            } else {
                var_r28 = shape_angle.y + (16384.0f * cM_ssin(mStickAngle) IF_DUSK(* (gz::movementSetting(2) ? -1.0f : 1.0f)));
            }

            cLib_addCalcAngleS(&shape_angle.y, var_r28, mpHIO->mSwim.m.mUnderwaterTurnRate, mpHIO->mSwim.m.mUnderwaterMaxTurn, mpHIO->mSwim.m.mUnderwaterMinTurn);
        }

        current.angle.y = shape_angle.y;
        var_f30 = 3.0f * cM_scos(shape_angle.y - temp_r29);
    } else if (!checkAttentionLock()) {
        if (checkInputOnR()) {
            temp_r29 = shape_angle.y;
            if (checkNoResetFlg0(FLG0_SWIM_UP)) {
                cLib_addCalcAngleS(&shape_angle.y, mMoveAngle, mpHIO->mSwim.m.mTurnRate, mpHIO->mSwim.m.mMaxTurn, mpHIO->mSwim.m.mMinTurn);
            } else {
                cLib_addCalcAngleS(&shape_angle.y, mMoveAngle, mpHIO->mSwim.m.mUnderwaterTurnRate, mpHIO->mSwim.m.mUnderwaterMaxTurn, mpHIO->mSwim.m.mUnderwaterMinTurn);
            }

            f32 var_f29;
            if (checkUnderMove0BckNoArc(ANM_SWIM_DASH)) {
                var_f29 = 1.0f;
            } else {
                var_f29 = mStickValue;
            }

            var_f30 = 3.0f * var_f29 * cM_scos(shape_angle.y - temp_r29);
            cLib_addCalcAngleS(&current.angle.y, shape_angle.y, 2, 0x2000, 0x1000);
        } else {
            var_f30 = 0.0f;
        }

        if (checkZeroSpeedF()) {
            current.angle.y = shape_angle.y;
        }
    } else {
        setShapeAngleToAtnActor(0);

        if (checkInputOnR()) {
            if (getDirectionFromCurrentAngle() == DIR_BACKWARD) {
                ANGLE_ADD_2(current.angle.y, 0x8000);
                mNormalSpeed *= -1.0f;
            }

            if (checkZeroSpeedF()) {
                current.angle.y = mMoveAngle;
            }

            temp_r29 = current.angle.y;
            if (checkNoResetFlg0(FLG0_SWIM_UP)) {
                cLib_addCalcAngleS(&current.angle.y, mMoveAngle, mpHIO->mSwim.m.mTurnRate, mpHIO->mSwim.m.mMaxTurn, mpHIO->mSwim.m.mMinTurn);
            } else {
                cLib_addCalcAngleS(&current.angle.y, mMoveAngle, mpHIO->mSwim.m.mUnderwaterTurnRate, mpHIO->mSwim.m.mUnderwaterMaxTurn, mpHIO->mSwim.m.mUnderwaterMinTurn);
            }

            var_f30 = mpHIO->mSwim.m.mAcceleration * mStickValue * cM_scos((s16)(current.angle.y - temp_r29));
        } else {
            var_f30 = 0.0f;
        }
    }

    f32 var_f28;
    if (50.0f < mNormalSpeed && !checkZoraWearAbility()) {
        var_f28 = mpHIO->mSwim.m.mDashDeceleration;
    } else {
        var_f28 = mpHIO->mSwim.m.mDeceleration;
    }

    setNormalSpeedF(var_f30, var_f28);

    if (dComIfGp_checkPlayerStatus0(0, 0x10)) {
        mNormalSpeed = 0.0f;
    }

    if (checkSwimNeckUpDown()) {
        s16 sp14;
        if (speed.y >= 0.0f) {
            var_f31 = -speed.y / mpHIO->mSwim.m.mMaxFloatUpSpeed;
            if (var_f31 < -1.0f) {
                var_f31 = -1.0f;
            }
            sp14 = 6144.0f * var_f31;
        } else {
            var_f31 = speed.y / maxFallSpeed;
            if (var_f31 > 1.0f) {
                var_f31 = 1.0f;
            }
            sp14 = 8192.0f * var_f31;
        }

        cLib_addCalcAngleS(&field_0x30a0, sp14, 5, 0x1000, 0x400);
    } else {
        field_0x30a0 = 0;
    }
}

int daAlink_c::checkSwimAction(int param_0) {
    f32 var_f31;
    if (checkWolf()) {
        if (getMoveBGActorName(mLinkAcch.m_gnd, 0) == fpcNm_Obj_ITA_e) {
            var_f31 = 200.0f;
        } else {
            var_f31 = mpHIO->mWolf.mWlSwim.m.mStartHeight;
        }
    } else {
        var_f31 = mpHIO->mSwim.m.mStartHeight;
    }

    if (checkNoResetFlg0(FLG0_UNK_80)
        && !checkNoResetFlg0(FLG0_WATER_IN_MOVE)
        && !checkModeFlg(0x40000)
        && mProcID != PROC_MAGNE_BOOTS_FLY
        && ((mProcID != PROC_WOLF_LOCK_ATTACK && mProcID != PROC_WOLF_LOCK_ATTACK_TURN) || mProcVar5.field_0x3012 == 0)
        && mDemo.getDemoMode() != daPy_demo_c::DEMO_UNK_17_e)
    {
        f32 var_f29;
        f32 var_f28;
        f32 var_f30;
        
        if (checkWolf()) {
            if (checkWolfDashMode()) {
                var_f29 = 50.0f;
            } else {
                var_f29 = 50.0f;
            }

            var_f28 = mpHIO->mWolf.mWlSwim.m.mMaxFallSpeed;
        } else {
            var_f29 = getSwimFrontMaxSpeed();
            var_f28 = getSwimMaxFallSpeed();
        }

        if (dComIfGp_checkPlayerStatus1(0, 0x10000)) {
            var_f30 = mLeftFootPos.y;
        } else if (dComIfGp_checkPlayerStatus1(0, 0x2000000)) {
            var_f30 = (-65.0f + current.pos.y) - var_f31;
        } else {
            var_f30 = current.pos.y;
        }

        if (mWaterY - var_f30 > var_f31 || (param_0 != 0 && mWaterY >= var_f30 && mWaterY - mLinkAcch.GetGroundH() > var_f31)) {
            cXyz sp14;
            offNoResetFlg0(FLG0_SWIM_UP);
            mZ2Link.setInWater(true);

            mMaxSpeed = var_f29;

            if (!param_0) {
                mNormalSpeed *= 0.75f;
            }

            if (mNormalSpeed >= mMaxSpeed) {
                mNormalSpeed = mMaxSpeed;
            }

            swimDeleteItem();

            if (checkEquipAnime()) {
                resetUpperAnime(UPPER_2, 3.0f);
            }

            field_0x3080 = 0;

            if (param_0) {
                if (current.pos.y - mWaterY > -5.0f) {
                    onNoResetFlg0(FLG0_SWIM_UP);
                    mZ2Link.setInWater(false);
                    return 0;
                }
                return 1;
            }

            if (checkModeFlg(2) && !checkPossibleWaterInMode()) {
                dComIfGp_getVibration().StartShock(VIBMODE_S_POWER2, 1, cXyz(0.0f, 1.0f, 0.0f));
                current.pos.y = var_f30 + var_f31;

                speed.y = 0.75f * field_0x3528.y;
                if (speed.y < var_f28) {
                    speed.y = var_f28;
                } else if (speed.y > 0.0f) {
                    speed.y = 0.0f;
                }

                if (checkWolf()) {
                    if (checkNoResetFlg2(FLG2_UNK_8)) {
                        daAlink_WANM anm;
                        if (cM_rnd() < 0.5f) {
                            anm = WANM_FLING_LEFT;
                            onNoResetFlg2(FLG2_WOLF_ENEMY_LEFT_THROW);
                        } else {
                            anm = WANM_FLING_RIGHT;
                            offNoResetFlg2(FLG2_WOLF_ENEMY_LEFT_THROW);
                        }
                        setWolfEnemyThrowUpperAnime(anm, 0.0f);
                    }

                    return procWolfSwimWaitInit(1);
                }

                if (mProcID == PROC_DIVE_JUMP) {
                    seStartOnlyReverb(Z2SE_AL_JUMP_DIVE_WATER);

                    if (checkZoraWearAbility()) {
                        field_0x3000 = 30;
                    }
                    return procSwimMoveInit();
                }

                return procSwimWaitInit(1);
            }

            if (checkBootsOrArmorHeavy() || checkPossibleWaterInMode()) {
                onNoResetFlg0(FLG0_WATER_IN_MOVE);
                return 0;
            }

            if (checkWolf()) {
                return procWolfSwimUpInit();
            }

            return procSwimUpInit();
        }
    } else if (!checkNoResetFlg0(FLG0_SWIM_UP) && !checkBootsOrArmorHeavy() && !checkPossibleWaterInMode() && !checkModeFlg(0x40000)) {
        if (checkNoResetFlg0(FLG0_UNK_80) && mWaterY - current.pos.y > var_f31) {
            if (checkWolf()) {
                return procWolfSwimWaitInit(0);
            }

            return procSwimWaitInit(0);
        }

        swimOutAfter(0);

        if (checkWolf()) {
            return procWolfWaitInit();
        }

        return procWaitInit();
    } else if (checkModeFlg(0x40000) && mProcID != PROC_CAUGHT && mProcID != PROC_DEAD) {
        return checkSwimOutAction();
    }

    return 0;
}

void daAlink_c::setSwimMoveAnime() {
    daPy_frameCtrl_c* framectrl_under0 = &mUnderFrameCtrl[0];
    daPy_frameCtrl_c* framectrl_upper2 = &mUpperFrameCtrl[2];

    f32 var_f31;
    f32 var_f26 = framectrl_under0->getFrame() * framectrl_under0->getEnd();

    if (field_0x3000 != 0 && !checkHookshotAnime()) {
        field_0x2f98 = 4;
    } else if (checkHookshotAnime() || (checkAttentionLock() && !getZoraSwim())) {
        field_0x3000 = 0;
        if (checkInputOnR()) {
            field_0x2f98 = getDirectionFromShapeAngle();
        } else if (field_0x2f98 >= 4 || mNormalSpeed < 3.0f) {
            field_0x2f98 = 0;
        }
    } else if (checkInputOnR() || field_0x2f98 >= 4 || mNormalSpeed < 3.0f) {
        field_0x2f98 = 0;
    }

    daAlink_ANM anm = (daAlink_ANM)field_0x3198;
    BOOL var_r26 = TRUE;
    BOOL var_r25 = FALSE;

    if (field_0x2f98 == 4) {
        f32 temp_f29 = 50.0f + mpHIO->mSwim.m.mUnderwaterButtonAdditionalSpeed;

        field_0x3478 = mpHIO->mSwim.m.mUnderwaterMinAnmSpeed;
        field_0x347c = mpHIO->mSwim.m.mUnderwaterMaxAnmSpeed;

        if (mMaxSpeed < 50.0f) {
            mMaxSpeed = 50.0f;
        } else if (doTrigger()) {
            mMaxSpeed += 0.75f;
            if (mMaxSpeed > temp_f29) {
                mMaxSpeed = temp_f29;
            }

            if (!checkSwimMoveHandAnime() && !checkZoraSwimDamageAnime()) {
                f32 var_f28;
                if (field_0x2060->getOldFrameMorfCounter() > 5.0f) {
                    var_f28 = -1.0f;
                } else {
                    var_f28 = 3.0f;
                }

                setUpperAnime(0x23F, UPPER_2, 1.0f, 0.0f, 0x28, var_f28);
                mProcVar5.field_0x3012 = 0;
                var_r25 = 1;
            } else if (framectrl_upper2->getFrame() > 25.0f) {
                mProcVar5.field_0x3012 = 1;
            }
        } else if (!checkSwimMoveHandAnime()) {
            cLib_chaseF(&mMaxSpeed, 50.0f, 0.4f);
        }

        var_f31 = 1.0f / 50.0f;

        if (checkZoraWearAbility() && (field_0x3198 == ANM_SWIM_DIVE || (field_0x3198 == ANM_SWIM_ZORA_START && !checkAnmEnd(framectrl_under0)))) {
            anm = ANM_SWIM_ZORA_START;
        } else {
            anm = ANM_SWIM_C;

            if (field_0x3198 == ANM_SWIM_ZORA_START) {
                var_r26 = FALSE;
                if (mProcVar4.field_0x3010 == 1) {
                    mProcVar4.field_0x3010 = 0;
                }
            }
        }
    } else if (field_0x2f98 == 0) {
        if (checkSwimDashMode() && checkUnderMove0BckNoArc(ANM_SWIM_DASH) && !checkAnmEnd(framectrl_under0)) {
            anm = ANM_SWIM_DASH;
        } else if (mNormalSpeed < 3.0f || checkHookshotAnime()) {
            anm = ANM_SWIM_WAIT;
            field_0x30d0 = 0;
        } else {
            anm = ANM_SWIM_A;
        }

        if (checkSwimDashMode()) {
            field_0x3478 = mpHIO->mSwim.m.mDashMinAnmSpeed;
            field_0x347c = mpHIO->mSwim.m.mDashMaxAnmSpeed;
            mMaxSpeed = 50.0f;
        } else {
            field_0x3478 = mpHIO->mSwim.m.mForwardMinAnmSpeed;
            field_0x347c = mpHIO->mSwim.m.mForwardMaxAnmSpeed;
            mMaxSpeed = getSwimFrontMaxSpeed();
        }

        var_f31 = 1.0f / mMaxSpeed;
    } else if (field_0x2f98 == 1) {
        anm = ANM_ATN_SWIM_BACK;
        field_0x3478 = mpHIO->mSwim.m.mBackwardMinAnmSpeed;
        field_0x347c = mpHIO->mSwim.m.mBackwardMaxAnmSpeed;

        if (checkZoraWearAbility()) {
            mMaxSpeed = 10.0f;
        } else {
            mMaxSpeed = 50.0f;
        }

        var_f31 = 1.0f / mMaxSpeed;
    } else {
        if (field_0x2f98 == 2) {
            anm = ANM_ATN_SWIM_LEFT;
        } else {
            anm = ANM_ATN_SWIM_RIGHT;
        }

        field_0x3478 = mpHIO->mSwim.m.mStrafeMinAnmSpeed;
        field_0x347c = mpHIO->mSwim.m.mStrafeMaxAnmSpeed;

        if (checkZoraWearAbility()) {
            mMaxSpeed = 12.0f;
        } else {
            mMaxSpeed = 50.0f;
        }

        var_f31 = 1.0f / mMaxSpeed;
    }

    field_0x347c -= field_0x3478;

    if (field_0x2f98 != 0) {
        field_0x30d0 = 0;
    }

    if (checkBootsOrArmorHeavy()) {
        anm = ANM_SWIM_WAIT;
        mMaxSpeed = 50.0f;
        if (mEquipItem != dItemNo_NONE_e && !checkHookshotAnime()) {
            setDoStatus(BUTTON_STATUS_PUT_AWAY);
        }
    }

    if (anm != field_0x3198) {
        if (field_0x3198 == ANM_SWIM_ZORA_START) {
            speed.y = 0.0f;
        }

        field_0x3198 = anm;

        if (checkUnderMove0BckNoArc(ANM_SWIM_DASH)) {
            field_0x30d2 = mpHIO->mSwim.m.field_0x5e;
        }

        if (anm == ANM_SWIM_WAIT) {
            setSingleAnimeBaseSpeed(ANM_SWIM_WAIT, mpHIO->mSwim.m.mWaitAnmSpeed, mpHIO->mSwim.m.mWaitInterpolation);
        } else {
            f32 morf;
            if (var_r26) {
                morf = mpHIO->mSwim.m.mMoveInterpolation;
            } else {
                morf = 0.0f;
            }
            setSingleAnimeBaseMorf(anm, morf);
        }
    }

    if (anm != ANM_SWIM_WAIT && anm != ANM_SWIM_DASH) {
        f32 temp_f30 = var_f31 * fabsf(mNormalSpeed);
        if (temp_f30 > 1.0f && field_0x2f98 == 4) {
            framectrl_under0->setRate(mpHIO->mSwim.m.mUnderwaterMaxAnmSpeed + ((temp_f30 - 1.0f) * mpHIO->mSwim.m.mUnderwaterAdditionalAnmSpeed));
        } else {
            framectrl_under0->setRate(field_0x3478 + (field_0x347c * temp_f30));
        }
    }

    if (checkSwimMoveHandAnime()) {
        if (framectrl_upper2->checkPass(17.0f)) {
            seStartOnlyReverb(Z2SE_AL_WATER_STROKE_L);
        }
    
        if (anm == ANM_SWIM_C) {
            framectrl_upper2->setRate(framectrl_under0->getRate());

            if (!var_r25 && framectrl_upper2->checkPass(0.0f)) {
                if (mProcVar5.field_0x3012 != 0) {
                    mProcVar5.field_0x3012 = 0;
                } else {
                    resetUpperAnime(UPPER_2, 3.0f);
                }
            }
        } else {
            resetUpperAnime(UPPER_2, -1.0f);
        }
    }

    maxFallSpeed = getSwimMaxFallSpeed();

    if (anm == ANM_SWIM_C || anm == ANM_SWIM_ZORA_START) {
        if (!checkZoraWearAbility()) {
            if (field_0x3080 != -0x3800) {
                setOldRootQuaternion(0x4000, 0, 0);
            }
            field_0x3080 = -0x3800;
        } else if (mProcVar4.field_0x3010 == 1) {
            cLib_addCalcAngleS(&field_0x3080, mProcVar3.field_0x300e, 5, 0x1000, 0x100);
        } else if (mProcVar4.field_0x3010 == 2) {
            cLib_addCalcAngleS(&field_0x3080, mProcVar3.field_0x300e, 5, 0x1000, 0x100);
            mProcVar4.field_0x3010 = 0;
        } else {
            s16 var_r24;
            if (checkInputOnR() && !checkEventRun()) {
                var_r24 = 13653.0f * cM_scos(mStickAngle) IF_DUSK(* (gz::movementSetting(3) ? -1.0f : 1.0f));
            } else {
                var_r24 = 0;
            }

            cLib_addCalcAngleS(&field_0x3080, var_r24, 5, 0x200, 0x80);
        }
    } else if (field_0x3080 != 0) {
        setOldRootQuaternion(field_0x3080, 0, 0);
        field_0x3080 = 0;
        mProcVar4.field_0x3010 = 0;

        if (!checkZoraWearAbility()) {
            mNormalSpeed = 0.0f;
        }
    }
}

int daAlink_c::checkNextActionWolf(int param_0) {
    if (checkDeadAction(1)) {
        return 1;
    }

    if (checkEndResetFlg1(ERFLG1_MIDNA_RIDE_SHOCK) &&
        (mProcID == PROC_WOLF_WAIT || mProcID == PROC_WOLF_SERVICE_WAIT ||
         mProcID == PROC_WOLF_TIRED_WAIT || (!checkInputOnR() && mProcID == PROC_WOLF_MOVE) ||
         mProcID == PROC_WOLF_LIE_START || mProcID == PROC_WOLF_LIE_MOVE ||
         mProcID == PROC_WOLF_ATN_AC_MOVE))
    {
        return procWolfMidnaRideShockInit();
    }

    if ((!checkAttentionState() ||
         (mProcID != PROC_WOLF_WAIT_ATTACK && mProcID != PROC_WOLF_JUMP_AT_NORMAL_LAND)) &&
        ((mProcID != PROC_WOLF_WAIT_SLIP && !param_0) || checkInputOnR()))
    {
        if (checkAttentionState()) {
            setSpeedAndAngleWolfAtn();
        } else {
            setSpeedAndAngleWolf();
        }
    }

    setFrontWallType();

    if (checkSlope()) {
        if (checkWolfDashMode()) {
            mMaxSpeed = mpHIO->mWolf.mWlSlide.m.mClimbingMaxSpeed;
        } else {
            mMaxSpeed = mpHIO->mWolf.mWlSlide.m.mClimbingMaxSpeedWeak;
        }
    } else if (checkFmChainGrabAnime()) {
        mMaxSpeed = 13.0f;
    } else if (mTargetedActor != NULL) {
        mMaxSpeed = mpHIO->mWolf.mWlAtnMove.m.mMaxSpeed;
    } else if (checkAttentionState()) {
        mMaxSpeed = mpHIO->mWolf.mWlMove.m.mGazeMaxSpeed;
    } else if (checkNoResetFlg1(FLG1_DASH_MODE)) {
        if (checkWolfSlowDash()) {
            mMaxSpeed = 70.0f;
        } else if (field_0x2fc7 == 2) {
            mMaxSpeed = mpHIO->mWolf.mWlMove.m.mADashMaxSpeedSlow2;
        } else {
            mMaxSpeed = 100.0f;
        }
    } else if (checkWolfDashMode()) {
        mMaxSpeed = mpHIO->mWolf.mWlMove.m.mMaxSpeed;
    } else {
        mMaxSpeed = mpHIO->mWolf.mWlMoveNoP.m.mMaxSpeed;
    }

    if (checkWolfGroundSpecialMode()) {
        return 1;
    }

    if (checkWolfLieContinue(0)) {
        return procWolfLieStartInit(0);
    }

    if (checkNextActionFromButton()) {
        return 1;
    }

    fopAc_ac_c* var_r4 = checkWolfRopeHit(&mTgCyls[0], mTgCyls[0].GetCP(), FALSE);
    if (var_r4 == NULL) {
        var_r4 = checkWolfRopeHit(&mTgCyls[1], &current.pos, FALSE);
    }

    if (var_r4 != NULL) {
        field_0x280c.setData(var_r4);
        return procWolfRopeMoveInit(0, 1);
    }

    if (param_0 && !checkInputOnR()) {
        return 0;
    }

    BOOL rt;
    if (!checkInputOnR() && mProcID == PROC_WOLF_WAIT_SLIP && checkWolfWaitSlipPolygon()) {
        rt = FALSE;
    } else if (checkAttentionState()) {
        rt = procWolfAtnActorMoveInit();
    } else {
        field_0x2f98 = 4;

        if (checkZeroSpeedF()) {
            if (!checkEventRun() && mStickValue > 0.85f && abs(field_0x3180) < 0x5000 &&
                (mProcID == PROC_WOLF_WAIT || mProcID == PROC_WOLF_MOVE) &&
                cLib_distanceAngleS(mMoveAngle, current.angle.y) > 0x7000)
            {
                if (checkEndResetFlg1(ERFLG1_UNK_200000)) {
                    rt = procWolfSlipTurnInit(0);
                } else {
                    rt = 0;
                }

                if (!rt && !checkEventRun()) {
                    rt = checkWaitAction();
                }
            } else {
                rt = checkWaitAction();
            }
        } else if (checkInputOnR() && mGndPolySpecialCode != dBgW_SPCODE_ICE &&
                   abs(field_0x3180) < 0x5000 &&
                   cLib_distanceAngleS(mMoveAngle, current.angle.y) > 0x7000 &&
                   ((checkWolfDashMode() &&
                     speedF / mMaxSpeed > mpHIO->mWolf.mWlMove.m.mSlipStartRate) ||
                    (!checkWolfDashMode() &&
                     speedF / mMaxSpeed > mpHIO->mWolf.mWlMoveNoP.m.mSlideStartRate)))
        {
            rt = procWolfSlipInit();
        } else {
            rt = procWolfMoveInit();
        }
    }

    return rt;
}

int daAlink_c::procWolfDashInit() {
    commonProcInit(PROC_WOLF_DASH);
    setSingleAnimeWolfParam(WANM_DASH_START, &mpHIO->mWolf.mWlMove.m.mADashAnm);
    setFootEffectProcType(3);
    current.angle.y = shape_angle.y;

    onNoResetFlg1(FLG1_DASH_MODE);
    mProcVar2.field_0x300c = 0;
    mProcVar3.field_0x300e = 0;

    if (checkWolfSlowDash()) {
        field_0x30d0 = mpHIO->mWolf.mWlMove.m.mADashDurationSlow;
        mMaxSpeed = 70.0f;

        if (mNormalSpeed < 70.0f) {
            mNormalSpeed = 70.0f;
        }
    } else if (field_0x2fc7 == 2) {
        mMaxSpeed = mpHIO->mWolf.mWlMove.m.mADashMaxSpeedSlow2;
        mMaxSpeed = mpHIO->mWolf.mWlMove.m.mADashMaxSpeedSlow2;

        if (mNormalSpeed < mpHIO->mWolf.mWlMove.m.mADashInitSpeedSlow2) {
            mNormalSpeed = mpHIO->mWolf.mWlMove.m.mADashInitSpeedSlow2;
        }
    } else {
        field_0x30d0 = mpHIO->mWolf.mWlMove.m.mADashDuration;
        mMaxSpeed = 100.0f;

        if (mNormalSpeed < 100.0f) {
            mNormalSpeed = 100.0f;
        }
    }

    return 1;
}

void daAlink_c::setSpeedAndAngleSwimWolf() {
    if (checkWolfDashMode()) {
        mMaxSpeed = 50.0f;
    } else {
        mMaxSpeed = 50.0f;
    }

    f32 speed;
    s16 prev_angle;
    if (checkInputOnR()) {
        prev_angle = current.angle.y;
        cLib_addCalcAngleS(&current.angle.y, mMoveAngle, mpHIO->mWolf.mWlSwim.m.mTurnRate,
                           mpHIO->mWolf.mWlSwim.m.mTurnMax, mpHIO->mWolf.mWlSwim.m.mTurnMin);

        speed = mStickValue * 3.0f * cM_scos(current.angle.y - prev_angle);
        shape_angle.y = current.angle.y;
    } else {
        speed = 0.0f;
    }

    if (checkWolfSwimDashAnime()) {
        speed = 3.0f;
    }

    if (checkAttentionState() && mProcID == PROC_WOLF_SWIM_WAIT) {
        if (mTargetedActor != NULL) {
            setShapeAngleToAtnActor(0);
        } else {
            cLib_addCalcAngleS(&shape_angle.y, field_0x2fe4, mpHIO->mWolf.mWlSwim.m.mIdleTurnRate,
                               mpHIO->mWolf.mWlSwim.m.mIdleTurnMax,
                               mpHIO->mWolf.mWlSwim.m.mIdleTurnMin);
        }

        current.angle.y = shape_angle.y;
    }

    setNormalSpeedF(speed, mpHIO->mWolf.mWlSwim.m.mDeceleration);

    if (dComIfGp_checkPlayerStatus0(0, 0x10)) {
        mNormalSpeed = 0.0f;
    }
}

namespace gz {

DEFINE_HOOK_SYMBOL("daAlink_c::setStartProcInit",int(daAlink_c*), Fast_setStartProcInit);
DEFINE_HOOK_SYMBOL("daAlink_c::initGravity",void(daAlink_c*), Fast_initGravity);
DEFINE_HOOK_SYMBOL("daAlink_c::procFrontRollInit",int(daAlink_c*), Fast_procFrontRollInit);
DEFINE_HOOK_SYMBOL("daAlink_c::getSwimFrontMaxSpeed",f32(const daAlink_c*), Fast_getSwimFrontMaxSpeed);
DEFINE_HOOK_SYMBOL("daAlink_c::getSwimMaxFallSpeed",f32(const daAlink_c*), Fast_getSwimMaxFallSpeed);
DEFINE_HOOK_SYMBOL("daAlink_c::setSpeedAndAngleSwim",void(daAlink_c*), Fast_setSpeedAndAngleSwim);
DEFINE_HOOK_SYMBOL("daAlink_c::checkSwimAction",int(daAlink_c* ,int), Fast_checkSwimAction);
DEFINE_HOOK_SYMBOL("daAlink_c::setSwimMoveAnime",void(daAlink_c*), Fast_setSwimMoveAnime);
DEFINE_HOOK_SYMBOL("daAlink_c::checkNextActionWolf",int(daAlink_c* ,int), Fast_checkNextActionWolf);
DEFINE_HOOK_SYMBOL("daAlink_c::procWolfDashInit",int(daAlink_c*), Fast_procWolfDashInit);
DEFINE_HOOK_SYMBOL("daAlink_c::setSpeedAndAngleSwimWolf",void(daAlink_c*), Fast_setSpeedAndAngleSwimWolf);
ModResult initFastMovement(){
 auto settingsResult=initMovementSettings();if(settingsResult!=MOD_OK)return settingsResult;
 toggle("fast_movement","Tools","Fast movement","Original GZ roll, swimming, iron-boots gravity and wolf dash speeds.");
 ModResult r=MOD_OK;
 r=guardedPre<Fast_setStartProcInit>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<int*>(result)=mods::arg<daAlink_c*>(a,0)->setStartProcInit();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_initGravity>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;mods::arg<daAlink_c*>(a,0)->initGravity();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_procFrontRollInit>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<int*>(result)=mods::arg<daAlink_c*>(a,0)->procFrontRollInit();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_getSwimFrontMaxSpeed>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<f32*>(result)=mods::arg<daAlink_c*>(a,0)->getSwimFrontMaxSpeed();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_getSwimMaxFallSpeed>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<f32*>(result)=mods::arg<daAlink_c*>(a,0)->getSwimMaxFallSpeed();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_setSpeedAndAngleSwim>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;mods::arg<daAlink_c*>(a,0)->setSpeedAndAngleSwim();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_checkSwimAction>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<int*>(result)=mods::arg<daAlink_c*>(a,0)->checkSwimAction(mods::arg<int>(a,1));return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_setSwimMoveAnime>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;mods::arg<daAlink_c*>(a,0)->setSwimMoveAnime();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_checkNextActionWolf>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<int*>(result)=mods::arg<daAlink_c*>(a,0)->checkNextActionWolf(mods::arg<int>(a,1));return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_procWolfDashInit>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;*static_cast<int*>(result)=mods::arg<daAlink_c*>(a,0)->procWolfDashInit();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 r=guardedPre<Fast_setSpeedAndAngleSwimWolf>([](ModContext*,void* a,void* result,void*){if(!on("fast_movement"))return HOOK_CONTINUE;mods::arg<daAlink_c*>(a,0)->setSpeedAndAngleSwimWolf();return HOOK_SKIP_ORIGINAL;});if(r!=MOD_OK)return r;
 return MOD_OK;
}
}
